<?php
$url = $this->url;
?>
    <div id="copyright" class="col-xs1 align-center">
      <p>Copyright &copy; David Ford | Transgress Inc.</p>
    </div>
<!-- .site-wrapper -->
</div>
    <!-- JavaScript -->
    <script src="<?php echo $url; ?>node_modules/jquery/dist/jquery.js"></script>
    <script src="<?php echo $url;?>node_modules/bootstrap/dist/js/bootstrap.js"></script>
    <script src="<?php echo $url; ?>node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="<?php echo $url; ?>/public/js/application.js"></script>
</body>
</html>
