<?php

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Monkedia Test -- David Ford</title>
    <meta name="description" content="This is a dev test for Monkedia">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?php echo $this->url; ?>node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $this->url; ?>node_modules/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet">
    <link href="<?php echo $this->url; ?>node_modules/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet">
    <link href="<?php echo $this->url; ?>public/css/style.css" rel="stylesheet">
</head>
<body>
  <div class="site-wrapper container">
    <header class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
      <a class="navbar-brand" href="<?php echo $this->url; ?>">Monkedia Test</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle Navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                <a class="nav-link" href="<?php echo $this->url; ?>login">Login <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->url; ?>logout">Logout</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<?php echo $this->url; ?>register">Register</a>
                </li> 
              </ul>
            </div>
      </nav>
    </header>
