<?php

?>
<div class="jumbotron">
    <div class="col-xl-7 align-center">
    <div class="container-fluid align-center">
        <h1>Welcome, to the Monkedia Test Page</h1>
    </div>
    <div id="call-to-action" class="container-fluid align-center">
        <h2><a href="<?php echo $this->url; ?>login">Login</a> to list clients.</h2>
        <h2>Don't have an account? That's ok!</h2>
        <h3> You can Register <a href="<?php echo $this->url; ?>register">Here</a></h3>
    </div>
    <div id="disclaimer" class="container-fluid align-center">
        <p>P.S. I am not a designer, so I apologize beforehand if the design of this page is bland.</p>
        <p>P.S.S. Although I am a capable frontend dev, I much prefer backend, as can be witnessed reviewing the code, designing and coding the MVC framework was fun (I coded it from scratch). But frontend work to me is much more tedious. (I am much better when I have a prototype or wireframe from a designer to work from)</p>
    </div>
    </div>
</div>
